name: CI

on:
  # Runs on Every Push
  push:
  # Runs on Pull Requests
  pull_request:
  workflow_dispatch:

env:
  MPW_TAG: gfmpw-0f
  USER_ID: 00000001
  CACHE_KEY: 0
  PDK: gf180mcuC
  STD_CELL_LIBRARY: gf180mcu_fd_sc_mcu7t5v0
  STD_CELL_LIBRARY_OPT: gf180mcu_fd_sc_mcu7t5v0

jobs:
  tapeout:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: cache conda
        uses: actions/cache@v3
        with:
          path: ~/conda_pkgs_dir
          key:
            ${{ runner.os }}-${{ env.CACHE_KEY }}-conda

      - name: setup miniconda
        uses: conda-incubator/setup-miniconda@v2.2.0
        with:
          installer-url: https://github.com/proppy/conda-eda/releases/download/v0.0-1429-gad6ae78/digital.gf180mcuc-0-Linux-x86_64.sh
          auto-activate-base: true
          activate-environment: ""
          channel-priority: strict
          use-only-tar-bz2: true

      - name: setup env
        run: |
          echo $CONDA/bin >> $GITHUB_PATH
          echo "PDK_ROOT=$CONDA/share/pdk" >> $GITHUB_ENV

      - name: test tools
        run: |
          yosys --version
          openroad -version
          magic -dnull -noconsole --version
          netgen -batch quit
      
      - name: run flow
        run: |
          make user_proj_example
          make user_project_wrapper

      - name: run precheck
        continue-on-error: true
        run: |
          make run-precheck

      - name: run timing
        continue-on-error: true        
        run: |
          make setup-timing-scripts
          make extract-parasitics
          make create-spef-mapping
          make caravel-sta

      - name: run tapeout
        continue-on-error: true        
        run: |
          make set_user_id
          make gpio_defaults
          make ship

      - name: archive gds
        uses: actions/upload-artifact@v2
        with:
          name: gds
          path: |
            /home/runner/work/caravel_user_project/caravel_user_project/gds/*
